# Generated by Django 3.1.5 on 2021-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0005_auto_20210301_1239'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ManyToManyField(help_text='选择该测验涵盖的主题', to='siteindex.Topic'),
        ),
    ]
