# Generated by Django 3.1.5 on 2021-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210310_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='required_credit',
            field=models.IntegerField(default=0, help_text='开始测验要求的已有学分'),
        ),
    ]
