# Generated by Django 3.1.5 on 2021-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_required_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='credit',
            field=models.IntegerField(default=1, help_text='完成该测验能获得的学分'),
        ),
    ]
