# Generated by Django 3.1.7 on 2021-04-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0014_auto_20210401_1558'),
        ('quiz', '0012_auto_20210312_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='siteindex.lesson'),
        ),
    ]
