# Generated by Django 3.1.7 on 2021-04-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_quiz_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='required_credit',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
