# Generated by Django 3.1.7 on 2021-04-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20210405_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['quiz', '-score']},
        ),
    ]
