# Generated by Django 3.1.7 on 2021-04-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20210405_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
