# Generated by Django 3.1.7 on 2021-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20210405_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
