# Generated by Django 3.1.5 on 2021-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0004_lecturer_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='status',
            field=models.CharField(blank=True, choices=[('a', '未学习'), ('b', '学习中'), ('c', '已学习')], default='a', max_length=1),
        ),
    ]
