# Generated by Django 3.1.5 on 2021-03-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0006_lessoncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(help_text='该门课程的介绍', max_length=10000)),
                ('syllabus', models.ImageField(blank=True, null=True, upload_to='syllabus')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteindex.course'),
        ),
    ]
