# Generated by Django 3.1.5 on 2021-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0007_auto_20210313_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
