# Generated by Django 3.1.7 on 2021-04-01 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteindex', '0012_auto_20210401_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_finished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished', to='siteindex.lesson')),
                ('lesson_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='siteindex.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
