# Generated by Django 3.1.7 on 2021-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0013_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='lesson_finished',
        ),
        migrations.AddField(
            model_name='record',
            name='lesson_finished',
            field=models.ManyToManyField(related_name='finished', to='siteindex.Lesson'),
        ),
        migrations.RemoveField(
            model_name='record',
            name='lesson_selected',
        ),
        migrations.AddField(
            model_name='record',
            name='lesson_selected',
            field=models.ManyToManyField(related_name='selected', to='siteindex.Lesson'),
        ),
    ]
