# Generated by Django 3.1.7 on 2021-04-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0014_auto_20210401_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='precondition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precond_of', to='siteindex.lesson'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lesson_finished',
            field=models.ManyToManyField(blank=True, null=True, related_name='finished', to='siteindex.Lesson'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lesson_selected',
            field=models.ManyToManyField(blank=True, null=True, related_name='selected', to='siteindex.Lesson'),
        ),
    ]
