# Generated by Django 3.1.7 on 2021-04-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0016_lecturer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', '当前应用'), ('b', '候补1'), ('c', '候补2')], default='a', max_length=1, unique=True)),
                ('intro', models.TextField(blank=True, help_text='课程大纲介绍', max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='syllabus')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
