# Generated by Django 3.1.7 on 2021-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0017_auto_20210405_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='lesson_selected',
        ),
        migrations.AlterField(
            model_name='record',
            name='lesson_finished',
            field=models.ManyToManyField(blank=True, related_name='finished', to='siteindex.Lesson'),
        ),
    ]
