# Generated by Django 3.1.7 on 2021-04-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteindex', '0016_lecturer_user'),
        ('discussboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.AddField(
            model_name='board',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='siteindex.lesson'),
        ),
    ]
